### ISSUE TITLE
It looks like there is an issue with this.characteristicMap when the heating mode is AUTO

### ISSUE THREAD

**Issue by gorathe** [rahulpilani/homebridge-nexia-thermostat-ts#1]
When the thermostat is set to AUTO rather than HEAT, COOL, or OFF then the following message is reported in the homebridge.log file:

[01/03/2021, 03:54:49] [homebridge-nexia-thermostat-ts] This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info.

The problem is to do with how the characteristicMap is being initialized:

        this.characteristicMap.set("COOL", this.Characteristic.CurrentHeatingCoolingState.COOL);
        this.characteristicMap.set("HEAT", this.Characteristic.CurrentHeatingCoolingState.HEAT);
        this.characteristicMap.set("AUTO", this.Characteristic.CurrentHeatingCoolingState.AUTO);
        this.characteristicMap.set("OFF", this.Characteristic.CurrentHeatingCoolingState.OFF);

There is no such constant as this.Characteristic.CurrentHeatingCoolingState.AUTO, only the HEAT/COOL/OFF versions.

**Comment by gorathe** [comment]
I've lodged an issue with the HAP-NodeJS folks.

**Comment by rahulpilani** [comment]
@gorathe can you link to the HAP-NodeJs issue here?

**Comment by gorathe** [comment]
Here's a link: https://github.com/homebridge/HAP-NodeJS/issues/888#issue-819895693

It turns out that it isn't a bug with HAP-NodeJS; The Characteristic.CurrentHeatingCoolingState.XXXX constants are there to describe what the HVAC is actually doing at the moment, so heating, cooling, or off, rather than what it is set to do: off, heat, cool, or auto.

I am doing some reading to see what should be used.

**Comment by gorathe** [comment]
Characteristic.TargetHeatingCoolingState.XXXX - 'Target' is a bit of a rubbish name if you ask me.
