### ISSUE TITLE
Can't seem to get nexia-api installed

### ISSUE THREAD

**Issue by jfmach** [rahulpilani/homebridge-nexia-thermostat-ts#3]
Hello,

I am having a problem with the install steps. If I try to npm install -g @cdmnky/nexia-api I get errors, and so I can't execute step 5 to retrieve the API Key and Mobile ID:

```
pi@homebridge:~/.homebridge$ sudo npm install -g @cdmnky/nexia-api
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@0.4.3: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 58 packages, and audited 59 packages in 7s

2 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
``` 

```
pi@homebridge:~/.homebridge$ node nexia.js 
/var/lib/homebridge/nexia.js:3
nexiaApi.connect(activation_code).then((api) => {
^

ReferenceError: nexiaApi is not defined
    at Object.<anonymous> (/var/lib/homebridge/nexia.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

I tried on two different machines, tried older releases of npm / node. but I always get the same errors... I'm not sure what I'm doing wrong.

Thank you,

- Jeff

**Comment by jfmach** [comment]
Disregard I figured it out. Had to add require to the script

**Comment by wootenkb** [comment]
I'm having the exact same issue. Can you elaborate on how you solved it? Thank you

**Comment by jfmach** [comment]
in nexia.js I had to add a line with the "require" statement with the path to where nexiaApi was installed

**Comment by jfmach** [comment]
@wootenkb did you manage to get it working?
See here: https://raw.githubusercontent.com/rahulpilani/homebridge-nexia-thermostat-ts/master/README.md

The require statement is on the same line as the backticks so that's why it doesn't show up. Add this at the top of your script:
`const nexiaApi = require('@cdmnky/nexia-api');
`

**Comment by QuarterSwede** [comment]
> in nexia.js I had to add a line with the "require" statement with the path to where nexiaApi was installed

Where can you find where it's installed? For me it looks like it never actually does and I get the exact same warnings on install of the api.
